# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-customer-receiver-messages:
    build:
      target: development
    image: ffc-sfd-customer-receiver-messages-development
    container_name: ffc-sfd-customer-receiver-messages-development
    ports:
      - "3012:3012"
      - "9012:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json