services:
  ffc-sfd-customer-receiver-messages:
    build:
      context: .
      target: production
    image: ffc-sfd-customer-receiver-messages
    container_name: ffc-sfd-customer-receiver-messages
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-customer-receiver-messages-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_HOST: ${MESSAGE_HOST}
      MESSAGE_USER: ${MESSAGE_USER}
      MESSAGE_PASSWORD: ${MESSAGE_PASSWORD}
      MESSAGES_SUBSCRIPTION_ADDRESS: ${MESSAGES_SUBSCRIPTION_ADDRESS}-${DEV_SUFFIX}
      MESSAGES_TOPIC_ADDRESS: ${MESSAGES_TOPIC_ADDRESS}-${DEV_SUFFIX}
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT}
      COSMOS_KEY: ${COSMOS_KEY}
