- key: NODE_ENV
  value: "production"
- key: PORT
  value: "3012"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"
- key: MESSAGES_TOPIC_ADDRESS
  value: "fcp-sfd-customer-messages"
- key: MESSAGES_SUBSCRIPTION_ADDRESS
  value: "fcp-sfd-customer-receiver-messages"